name: active_ecommerce_flutter
description: This is the flutter mobile application for active ecommerce cms

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  after_init: ^0.1.2
  bordered_text: ^2.0.0
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  clipboard: ^0.1.2+8
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.3
  dotted_line: ^3.0.1
  dropdown_search: ^2.0.0
  expandable: ^5.0.1
  firebase_messaging: ^10.0.8
  flutter:
    sdk: flutter
  flutter_chat_bubble: ^2.0.0
  flutter_countdown_timer: ^4.1.0
  flutter_facebook_login: ^3.0.0
  flutter_gen: ^4.1.6
  flutter_html: ^2.1.5
  flutter_icons: ^1.1.0
  flutter_localizations:
    sdk: flutter
  flutter_math_fork: ^0.5.0
  flutter_rating_bar: ^4.0.0
  flutter_svg: null
  flutter_typeahead: ^3.2.1
  google_fonts: ^2.1.0
  google_sign_in: ^5.1.1
  http: ^0.13.4
  image_picker: ^0.8.4+2
  intl: null
  intl_phone_number_input: ^0.7.0+2
  json_annotation: ^4.1.0
  logging: ^1.0.2
  one_context: ^1.1.1
  package_info: ^2.0.2
  permission_handler: ^6.1.3
  photo_view: ^0.13.0
  progress_dialog: ^1.2.4
  provider: null
  rename: ^1.3.0
  shared_preferences: ^2.0.8
  shared_value: ^2.1.0
  shimmer: ^2.0.0
  social_share: ^2.0.4
  splashscreen: ^1.3.5
  timeline_list: ^0.0.3
  timeline_tile: ^2.0.0
  toast: ^0.1.5
  url_launcher: ^6.0.12
  webview_flutter: ^2.1.1

dev_dependencies:
  build_runner: ^2.1.4
  flutter_gen_runner: null
  flutter_launcher_icons: ^0.9.2
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: null
  flutter_test:
    sdk: flutter
  google_maps_flutter: ^2.0.11
  json_serializable: ^5.0.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - dummy_assets/
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
